color: rose
fieldLayouts:
  b9957e7b-b20d-48c4-b31a-76db1ed282d9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-03-04T22:01:31+00:00'
            elementCondition: null
            fieldUid: 8caa03f8-3adc-432b-ab99-ed34ee3d38cf # Button Label
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ece43a07-f2b1-42c2-9b26-415443b9a8be
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-04T22:01:31+00:00'
            elementCondition: null
            fieldUid: 9bba6d89-3667-47b0-ba07-ab4f7c4b94f7 # Button Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0846dcb3-0044-4a53-a193-09ca890395d1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 62f7ebde-04cf-4cd4-82b3-276e920f6a93
        userCondition: null
handle: buttonMatrix
hasTitleField: false
icon: circle-dot
name: Button
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
