color: red
fieldLayouts:
  369e007d-93dd-462b-a87a-8bc135cfd3ea:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-03T22:00:32+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: 'Campground Name'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3c3be239-70af-448c-9528-40e964e64ff0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-03T22:02:11+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ebc895af-2bcc-4634-a4d3-0731e07c7375 # Description
            handle: null
            includeInCards: false
            instructions: null
            label: Description
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 28728bc7-f698-4d3d-aea2-e5d213f78071
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-03T22:02:11+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 9bba6d89-3667-47b0-ba07-ab4f7c4b94f7 # Button Link
            handle: null
            includeInCards: false
            instructions: null
            label: Website
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c9d0abbd-cc86-438a-a20c-3d1bd7fb5866
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-22T20:51:17+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ab6c365b-93ed-48d3-a3bc-379b26d99166 # Distance from Venue
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 16ba0992-cf5a-4f72-9570-57b0255ed61a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-03T22:02:11+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c21a1834-83f0-426e-8881-fbb41b038ee7 # Asset
            handle: null
            includeInCards: false
            instructions: null
            label: 'Campground Image'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0df68e2e-43fb-4f4a-8113-5cefdacd17f1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4678cea5-557f-4397-bf4e-f30a76468dd8
        userCondition: null
handle: camground
hasTitleField: true
icon: campground
name: Camground
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
