color: orange
fieldLayouts:
  b0f93685-c21f-4ca3-9bb6-64549992d964:
    cardView:
      - 'layoutElement:9691b6d5-581a-4387-94f0-43d23cdc63a4'
      - 'layoutElement:f615831b-24f3-405c-8661-86e024c53ddb'
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-03T22:03:55+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e0af3b6f-2107-4e08-88f3-34e2587cd12c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-03T22:06:59+00:00'
            elementCondition: null
            fieldUid: ebc895af-2bcc-4634-a4d3-0731e07c7375 # Description
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9691b6d5-581a-4387-94f0-43d23cdc63a4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-03T22:06:59+00:00'
            elementCondition: null
            fieldUid: ab6c365b-93ed-48d3-a3bc-379b26d99166 # Distance from Venue
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f615831b-24f3-405c-8661-86e024c53ddb
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6c9b8d1a-ba33-4f24-a0da-4154e9384645
        userCondition: null
handle: plane
hasTitleField: true
icon: plane
name: Plane
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
