color: null
fieldLayouts:
  962f948a-11e3-45fa-9d5f-205c80366984:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-03T22:14:34+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6b39ae57-1f60-4872-ada8-4de68b1daeaa
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-03T22:14:34+00:00'
            elementCondition: null
            fieldUid: 3ce8f18a-c45c-461a-8ce2-a066abb324be # Date
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d11dfcfc-a14b-4b9a-a8e2-ae45f23aa212
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-04T18:27:51+00:00'
            elementCondition: null
            fieldUid: 00bc33ef-75ef-4102-9833-38fa15127f72 # Start Time
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6e905731-cb51-49e2-b754-48d44ef2297f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-04T18:27:51+00:00'
            elementCondition: null
            fieldUid: 153b26c9-5add-4419-9e68-24b43ec3574a # End Time
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c51a39a5-c711-42ab-8168-714d52ebf873
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-03T22:14:34+00:00'
            elementCondition: null
            fieldUid: ebc895af-2bcc-4634-a4d3-0731e07c7375 # Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a68547ba-abd4-43c2-8adf-bfaf6a1fef3d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-03T22:14:34+00:00'
            elementCondition: null
            fieldUid: 6d3bee8f-1119-4e9e-98aa-f6f796dcfbb2 # PNW Fun Day Activities
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: caeaefd6-e585-4e5b-aabe-9e7debea4094
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 479e82a3-040d-4c96-9fac-23e1bd667956
        userCondition: null
handle: pnwFunDay
hasTitleField: true
icon: null
name: 'PNW Fun Day'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
