color: rose
fieldLayouts:
  122936fd-5207-4bda-b714-5868f2a45eb6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-03-13T06:11:35+00:00'
            elementCondition: null
            fieldUid: ebc895af-2bcc-4634-a4d3-0731e07c7375 # Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 210cea63-af22-4fb5-afa1-5ffd56fcb81b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-18T05:52:30+00:00'
            elementCondition: null
            fieldUid: bb1d76d6-ff43-4116-8a9c-db76de9b852d # Form Header
            handle: form1
            includeInCards: false
            instructions: null
            label: 'Intro Form Header'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0beb3121-3d84-47e7-bec3-8ece87f11dcf
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-18T05:52:30+00:00'
            elementCondition: null
            fieldUid: bb1d76d6-ff43-4116-8a9c-db76de9b852d # Form Header
            handle: form2
            includeInCards: false
            instructions: null
            label: 'General Info Form Header'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5c6241b6-4eea-492d-acb3-2d45167cc2cf
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-18T05:52:30+00:00'
            elementCondition: null
            fieldUid: bb1d76d6-ff43-4116-8a9c-db76de9b852d # Form Header
            handle: form3
            includeInCards: false
            instructions: null
            label: 'Events Form Header'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 400c19d5-54a2-4a8c-850f-37e78f3cf67a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-18T05:52:30+00:00'
            elementCondition: null
            fieldUid: bb1d76d6-ff43-4116-8a9c-db76de9b852d # Form Header
            handle: formSorry
            includeInCards: false
            instructions: null
            label: 'Sorry Form Header'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cac99483-86cf-40e2-9738-56b4defddc0f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1195d154-eb81-4690-9400-fae179795a28
        userCondition: null
handle: rsvp
hasTitleField: false
icon: people
name: RSVP
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: RSVP
titleTranslationKeyFormat: null
titleTranslationMethod: site
