allowPublicRegistration: true
deactivateByDefault: false
defaultGroup: 3c9bc0fa-4b01-49c0-b594-950d74f7f840 # Guests
photoSubpath: null
photoVolumeUid: null
require2fa: false
requireEmailVerification: true
validateOnPublicRegistration: false
