altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  f172d03c-4100-4f44-8473-181c86d0c4e1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-04T18:20:39+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 00e7c66e-41f3-4f6c-8486-a25e41454691
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 06ba6d77-25eb-4e3c-84f1-af11bb41239a
        userCondition: null
fs: uploads
handle: general
name: General
sortOrder: 1
subpath: general
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: transforms
