columnSuffix: null
handle: startTime
instructions: null
name: 'Start Time'
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: 30
translationKeyFormat: null
translationMethod: none
type: craft\fields\Time
