defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 53f5df1f-a8c2-48f6-92cb-98c2cdde3e25 # Home
handle: home
maxAuthors: 1
name: Home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  4be1c3c3-eeb9-45c6-ae81-243238b64098: # Wedding
    enabledByDefault: true
    hasUrls: true
    template: _pages/home
    uriFormat: __home__
type: single
