defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 16dc5a83-91b9-4f56-bca8-14d66a80407d # RSVP
handle: rsvp
maxAuthors: 1
name: RSVP
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  4be1c3c3-eeb9-45c6-ae81-243238b64098: # Wedding
    enabledByDefault: true
    hasUrls: true
    template: _pages/rsvp.twig
    uriFormat: rsvp
type: single
